### ISSUE TITLE
Clarify if it is necessary to use the mixer build chroots

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/how-to-clear#11]
It is not clear if the command mixer build chroots is still necessary in the mixing process.

Documentation that can be found here
https://github.com/clearlinux/how-to-clear/blob/master/04-mixing.md

Does not mention it and the mixer build -h command does not show the 'chroot' command at all. I can still execute it, though, and get valid results.

**Comment by ahkok** [comment]
@matthewrsj

**Comment by matthewrsj** [comment]
`mixer build chroots` is a hidden alias to `mixer build bundles`. The concept of building a chroot-per-bundle is no longer relevant as we only build one chroot (implementation detail).

`mixer build bundles` is the correct command and is what is being run when you invoke `mixer build chroots`

**Comment by ahkok** [comment]
BTW I've opted in this document to avoid partial builds and always issue `sudo mixer build all` for each full step since that is the simplest method to use mixer without complications. For this reason `mixer build chroots` or `bundles` isn't even mentioned as something important in this document.

**Comment by mpurzynski** [comment]
Got it! Thank you for the explanation, consider my request invalid and
let's only keep doing what the best practice is telling us :)
