### ISSUE TITLE
Usage of SimpleHTTPServer vs nginx

### ISSUE THREAD

**Issue by sysarcher** [clearlinux/how-to-clear#16]
Hi,

I was wondering if it'd be advisable to use `python -m http.server` instead of nginx in the [deployment chapter](https://github.com/clearlinux/how-to-clear/blob/master/05-deploying.md#nginx)?

`nginx` might be complicated for people new to webservers (especially those coming from embedded development backgrounds)...

This is just an enhancement proposal.

**Comment by bryteise** [comment]
Yes, that'd be a reasonable change to avoid potential issues in going through a tutorial. That said having a more robust system setup to be completely documented has benefits as well.

**Comment by sysarcher** [comment]
@bryteise yes, I totally agree!! 

If you want me to submit a PR, I can submit one.. that is, if you guys want the change.

**Comment by bryteise** [comment]
I'll leave the final decision to @ahkok

**Comment by ahkok** [comment]
No thanks.

`python -m http.server` isn't a production level webserver and should never be used as such. It needlessly creates a large attack surface, for one.

The amount of text devoted to setting up nginx is reasonable, too. It's almost exactly chewed out, and if you can read and follow directions, it should be entirely clear. If it isn't, send corrections for that.

We want to show people how to run a responsible mix.

**Comment by sysarcher** [comment]
@ahkok alright. What you said makes a lot of sense!! I was just thinking from a first-user perspective.
