### ISSUE TITLE
Mixer: Docs incorrectly duplicate documentation that already exists

### ISSUE THREAD

**Issue by tmarcu** [clearlinux/how-to-clear#19]
Please remove everything starting from 
`## Initializing the workspace` down and provide a link to https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer

We should only be keeping 1 set of documentation and this is the official one that is given to new users.

**Comment by ahkok** [comment]
No. This isn't documentation.

This is a training handbook.

It is entirely reasonable that it duplicates content, as it is meant to cover the COMBINATION of tools used to achieve the goal.

It's reasonable to add thorough references and links where applicable. But the premise that one can only document something in one location is false.

**Comment by tmarcu** [comment]
It _incorrectly_ duplicates content...  it's spreading misinformation because you don't link anywhere to the **actual** documentation of how to use it, and then trivial tasks don't work because the correct workflow and reasoning was never explored. 
I don't see the point of maintaining two exactly similar documents in separate locations at all. If you want to have it here, then remove the guide on clearlinux.org; it's just adding engineering work for the mixer team and for you whenever one is updated to reflect tooling changes and updates, or it makes one of them out of date and people don't understand which one to follow, hitting bugs that would have otherwise been easily mitigated with proper documentation.

**Comment by ahkok** [comment]
Just tell me what is wrong. Or send a patch.

**Comment by ahkok** [comment]
> it's spreading misinformation because you don't link anywhere to the actual documentation of how to

#18  is intended to solve this
